### ISSUE TITLE
Unable to start live trading in 0.5.10 (paper and real trading)

### ISSUE THREAD

**Issue by SOGorman35** [enigmampc/catalyst#330]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10 Pro Version 1709 OS Build 16299.431
* Python Version: Python 2.7.13 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Catalyst: Miniconda
* Python packages: alembic==0.9.6
backports-abc==0.5
backports.functools-lru-cache==1.4
backports.shutil-get-terminal-size==1.0.0
backports.shutil-which==3.5.1
bcolz==0.12.1
bleach==2.1.2
boto3==1.6.3
botocore==1.9.3
Bottleneck==1.2.1
ccxt==1.13.42
certifi==2018.1.18
chardet==3.0.4
click==6.7
colorama==0.3.9
configparser==3.5.0
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.1
cytoolz==0.9.0
decorator==4.1.2
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.10
entrypoints==0.2.3
enum34==1.1.6
eth-abi==0.5.0
eth-keyfile==0.5.1
eth-keys==0.1.0b4
eth-utils==0.8.1
functools32==3.2.3.post2
futures==3.2.0
html5lib==1.0.1
idna==2.6
intervaltree==2.1.0
ipykernel==4.8.2
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.1.2
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.0
mistune==0.8.3
multipledispatch==0.4.9
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.0
notebook==5.4.0
numexpr==2.6.4
numpy==1.13.1
pandas==0.19.2
pandas-datareader==0.5.0
pandocfilters==1.4.2
pathlib2==2.3.0
patsy==0.4.1
pickleshare==0.7.4
prompt-toolkit==1.0.15
pycryptodome==3.4.11
Pygments==2.2.0
pyparsing==2.2.0
pysha3==1.0.2
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.2
pywinpty==0.5.1
pyzmq==17.0.0
qtconsole==4.3.1
redo==1.6
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==0.6.0
s3transfer==0.1.13
scandir==1.7
scikit-learn==0.19.0
scipy==0.19.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sortedcontainers==1.5.7
SQLAlchemy==1.1.14
statsmodels==0.8.0
subprocess32==3.2.7
TA-Lib==0.4.16
tables==3.4.2
terminado==0.8.1
testpath==0.3.1
toolz==0.8.2
tornado==5.0
traitlets==4.3.2
typing==3.6.4
urllib3==1.22
wcwidth==0.1.7
web3==4.0.0b7
webencodings==0.5.1
widgetsnbextension==3.1.4
win-unicode-console==0.5
wincertstore==0.2

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

Attempted to start live trading (first as paper, then double checked with real trading), and received the following error:

Traceback (most recent call last):
  File "c:\users\sogor\miniconda2\envs\catalyst\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\sogor\miniconda2\envs\catalyst\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\sogor\Miniconda2\envs\catalyst\Scripts\catalyst.exe\__main__.py", line 9, in <module>
  File "c:\users\sogor\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\sogor\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\sogor\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\sogor\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\sogor\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\sogor\miniconda2\envs\catalyst\lib\site-packages\catalyst\__main__.py", line 104, in _
    return f(*args, **kwargs)
  File "c:\users\sogor\miniconda2\envs\catalyst\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: live() got an unexpected keyword argument 'start'

* What did you expect to happen?

Live/simulated trading to begin.

* What happened instead?

The error message listed above.  No changes have been made to anything else beyond upgrading to 0.5.10.  Live trading worked in 0.5.9.

Here is how you can reproduce this issue on your machine:

# Reproduction Steps

1. Attempt to run catalyst live [additional parameters]

# Anything else?

I did some backtesting in Jupyter, and it still works fine.

...

Sincerely,
Sean

**Comment by lenak25** [comment]
Hi @SOGorman35 , thanks for reporting!

Could you please share the run command you are using \ `run_algorithm` function definition?

Thanks!

**Comment by SOGorman35** [comment]
I run from the command line.  An example (specifics removed for privacy) would be:

catalyst live -f sample.py -x exchange -c btc --capital-base 1 -n sample_output.

If it was real money trading, I'd also add --no-simulate-orders --auth-aliases exchange,auth

_Hopefully_ I'm not forgetting anything in there.

**Comment by AvishaiW** [comment]
Hi, The bug was fixed and we released a new version (0.5.11). Thanks for pointing it out!
